name: file_curator
channels:
    - conda-forge
dependencies:
    - python=3.14
    - fastapi
    - uvicorn
    - scikit-learn
    - watchdog
    - notebook
    - pytest
    - pip

    - pip:
       - python-dotenv